version: "3"
services:
  db:
    image: postgres:14.0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: superadmin
      POSTGRES_DB: blogDB
    ports:
      - "5432:5432"
    restart: on-failure
